#ifndef HWREG_H__24_06_2017__23_34
#define HWREG_H__24_06_2017__23_34

#include "types.h"

#define reg_MCR                         (*(u8* )0xFFFFE400)                                                           
#define reg_GSR                         (*(u8* )0xFFFFE401)     
#define reg_BCR                         (*(u16*)0xFFFFE402)     
#define reg_MBCR                        (*(u16*)0xFFFFE404)     
#define reg_TXPR                        (*(u16*)0xFFFFE406)     
#define reg_TXCR                        (*(u16*)0xFFFFE408)     
#define reg_TXACK                       (*(u16*)0xFFFFE40A)     
#define reg_ABACK                       (*(u16*)0xFFFFE40C)     
#define reg_RXPR                        (*(u16*)0xFFFFE40E)     
#define reg_RFPR                        (*(u16*)0xFFFFE410)     
#define reg_IRR                         (*(u16*)0xFFFFE412)     
#define reg_MBIMR                       (*(u16*)0xFFFFE414)                                                           
#define reg_IMR                         (*(u16*)0xFFFFE416)                                                           
#define reg_REC                         (*(u8* )0xFFFFE418)     
#define reg_TEC                         (*(u8* )0xFFFFE419)     
#define reg_UMSR                        (*(u16*)0xFFFFE41A)     
#define reg_LAFML                       (*(u16*)0xFFFFE41C)     
#define reg_LAFMH                       (*(u16*)0xFFFFE41E)     
#define reg_MC0_1                       (*(u8* )0xFFFFE420)     
#define reg_MC0_2                       (*(u8* )0xFFFFE421)     
#define reg_MC0_3                       (*(u8* )0xFFFFE422)     
#define reg_MC0_4                       (*(u8* )0xFFFFE423)     
#define reg_MC0_5                       (*(u8* )0xFFFFE424)     
#define reg_MC0_6                       (*(u8* )0xFFFFE425)     
#define reg_MC0_7                       (*(u8* )0xFFFFE426)     
#define reg_MC0_8                       (*(u8* )0xFFFFE427)     
#define reg_MC1_1                       (*(u8* )0xFFFFE428)     
#define reg_MC1_2                       (*(u8* )0xFFFFE429)     
#define reg_MC1_3                       (*(u8* )0xFFFFE42A)     
#define reg_MC1_4                       (*(u8* )0xFFFFE42B)     
#define reg_MC1_5                       (*(u8* )0xFFFFE42C)     
#define reg_MC1_6                       (*(u8* )0xFFFFE42D)     
#define reg_MC1_7                       (*(u8* )0xFFFFE42E)     
#define reg_MC1_8                       (*(u8* )0xFFFFE42F)     
#define reg_MC2_1                       (*(u8* )0xFFFFE430)     
#define reg_MC2_2                       (*(u8* )0xFFFFE431)     
#define reg_MC2_3                       (*(u8* )0xFFFFE432)     
#define reg_MC2_4                       (*(u8* )0xFFFFE433)     
#define reg_MC2_5                       (*(u8* )0xFFFFE434)     
#define reg_MC2_6                       (*(u8* )0xFFFFE435)     
#define reg_MC2_7                       (*(u8* )0xFFFFE436)     
#define reg_MC2_8                       (*(u8* )0xFFFFE437)     
#define reg_MC3_1                       (*(u8* )0xFFFFE438)     
#define reg_MC3_2                       (*(u8* )0xFFFFE439)     
#define reg_MC3_3                       (*(u8* )0xFFFFE43A)     
#define reg_MC3_4                       (*(u8* )0xFFFFE43B)     
#define reg_MC3_5                       (*(u8* )0xFFFFE43C)     
#define reg_MC3_6                       (*(u8* )0xFFFFE43D)     
#define reg_MC3_7                       (*(u8* )0xFFFFE43E)     
#define reg_MC3_8                       (*(u8* )0xFFFFE43F)     
#define reg_MC4_1                       (*(u8* )0xFFFFE440)     
#define reg_MC4_2                       (*(u8* )0xFFFFE441)     
#define reg_MC4_3                       (*(u8* )0xFFFFE442)     
#define reg_MC4_4                       (*(u8* )0xFFFFE443)     
#define reg_MC4_5                       (*(u8* )0xFFFFE444)     
#define reg_MC4_6                       (*(u8* )0xFFFFE445)     
#define reg_MC4_7                       (*(u8* )0xFFFFE446)     
#define reg_MC4_8                       (*(u8* )0xFFFFE447)     
#define reg_MC5_1                       (*(u8* )0xFFFFE448)     
#define reg_MC5_2                       (*(u8* )0xFFFFE449)     
#define reg_MC5_3                       (*(u8* )0xFFFFE44A)     
#define reg_MC5_4                       (*(u8* )0xFFFFE44B)     
#define reg_MC5_5                       (*(u8* )0xFFFFE44C)     
#define reg_MC5_6                       (*(u8* )0xFFFFE44D)     
#define reg_MC5_7                       (*(u8* )0xFFFFE44E)     
#define reg_MC5_8                       (*(u8* )0xFFFFE44F)     
#define reg_MC6_1                       (*(u8* )0xFFFFE450)     
#define reg_MC6_2                       (*(u8* )0xFFFFE451)     
#define reg_MC6_3                       (*(u8* )0xFFFFE452)     
#define reg_MC6_4                       (*(u8* )0xFFFFE453)     
#define reg_MC6_5                       (*(u8* )0xFFFFE454)     
#define reg_MC6_6                       (*(u8* )0xFFFFE455)     
#define reg_MC6_7                       (*(u8* )0xFFFFE456)     
#define reg_MC6_8                       (*(u8* )0xFFFFE457)     
#define reg_MC7_1                       (*(u8* )0xFFFFE458)     
#define reg_MC7_2                       (*(u8* )0xFFFFE459)     
#define reg_MC7_3                       (*(u8* )0xFFFFE45A)     
#define reg_MC7_4                       (*(u8* )0xFFFFE45B)     
#define reg_MC7_5                       (*(u8* )0xFFFFE45C)     
#define reg_MC7_6                       (*(u8* )0xFFFFE45D)     
#define reg_MC7_7                       (*(u8* )0xFFFFE45E)     
#define reg_MC7_8                       (*(u8* )0xFFFFE45F)     
#define reg_MC8_1                       (*(u8* )0xFFFFE460)     
#define reg_MC8_2                       (*(u8* )0xFFFFE461)     
#define reg_MC8_3                       (*(u8* )0xFFFFE462)     
#define reg_MC8_4                       (*(u8* )0xFFFFE463)     
#define reg_MC8_5                       (*(u8* )0xFFFFE464)     
#define reg_MC8_6                       (*(u8* )0xFFFFE465)     
#define reg_MC8_7                       (*(u8* )0xFFFFE466)     
#define reg_MC8_8                       (*(u8* )0xFFFFE467)     
#define reg_MC9_1                       (*(u8* )0xFFFFE468)     
#define reg_MC9_2                       (*(u8* )0xFFFFE469)     
#define reg_MC9_3                       (*(u8* )0xFFFFE46A)     
#define reg_MC9_4                       (*(u8* )0xFFFFE46B)     
#define reg_MC9_5                       (*(u8* )0xFFFFE46C)     
#define reg_MC9_6                       (*(u8* )0xFFFFE46D)     
#define reg_MC9_7                       (*(u8* )0xFFFFE46E)     
#define reg_MC9_8                       (*(u8* )0xFFFFE46F)     
#define reg_MC10_1                      (*(u8* )0xFFFFE470)     
#define reg_MC10_2                      (*(u8* )0xFFFFE471)     
#define reg_MC10_3                      (*(u8* )0xFFFFE472)     
#define reg_MC10_4                      (*(u8* )0xFFFFE473)     
#define reg_MC10_5                      (*(u8* )0xFFFFE474)     
#define reg_MC10_6                      (*(u8* )0xFFFFE475)     
#define reg_MC10_7                      (*(u8* )0xFFFFE476)     
#define reg_MC10_8                      (*(u8* )0xFFFFE477)     
#define reg_MC11_1                      (*(u8* )0xFFFFE478)     
#define reg_MC11_2                      (*(u8* )0xFFFFE479)     
#define reg_MC11_3                      (*(u8* )0xFFFFE47A)     
#define reg_MC11_4                      (*(u8* )0xFFFFE47B)     
#define reg_MC11_5                      (*(u8* )0xFFFFE47C)     
#define reg_MC11_6                      (*(u8* )0xFFFFE47D)     
#define reg_MC11_7                      (*(u8* )0xFFFFE47E)     
#define reg_MC11_8                      (*(u8* )0xFFFFE47F)     
#define reg_MC12_1                      (*(u8* )0xFFFFE480)     
#define reg_MC12_2                      (*(u8* )0xFFFFE481)     
#define reg_MC12_3                      (*(u8* )0xFFFFE482)     
#define reg_MC12_4                      (*(u8* )0xFFFFE483)     
#define reg_MC12_5                      (*(u8* )0xFFFFE484)     
#define reg_MC12_6                      (*(u8* )0xFFFFE485)     
#define reg_MC12_7                      (*(u8* )0xFFFFE486)     
#define reg_MC12_8                      (*(u8* )0xFFFFE487)     
#define reg_MC13_1                      (*(u8* )0xFFFFE488)     
#define reg_MC13_2                      (*(u8* )0xFFFFE489)     
#define reg_MC13_3                      (*(u8* )0xFFFFE48A)     
#define reg_MC13_4                      (*(u8* )0xFFFFE48B)     
#define reg_MC13_5                      (*(u8* )0xFFFFE48C)     
#define reg_MC13_6                      (*(u8* )0xFFFFE48D)     
#define reg_MC13_7                      (*(u8* )0xFFFFE48E)     
#define reg_MC13_8                      (*(u8* )0xFFFFE48F)     
#define reg_MC14_1                      (*(u8* )0xFFFFE490)     
#define reg_MC14_2                      (*(u8* )0xFFFFE491)     
#define reg_MC14_3                      (*(u8* )0xFFFFE492)     
#define reg_MC14_4                      (*(u8* )0xFFFFE493)     
#define reg_MC14_5                      (*(u8* )0xFFFFE494)     
#define reg_MC14_6                      (*(u8* )0xFFFFE495)     
#define reg_MC14_7                      (*(u8* )0xFFFFE496)     
#define reg_MC14_8                      (*(u8* )0xFFFFE497)     
#define reg_MC15_1                      (*(u8* )0xFFFFE498)     
#define reg_MC15_2                      (*(u8* )0xFFFFE499)     
#define reg_MC15_3                      (*(u8* )0xFFFFE49A)     
#define reg_MC15_4                      (*(u8* )0xFFFFE49B)     
#define reg_MC15_5                      (*(u8* )0xFFFFE49C)     
#define reg_MC15_6                      (*(u8* )0xFFFFE49D)     
#define reg_MC15_7                      (*(u8* )0xFFFFE49E)     
#define reg_MC15_8                      (*(u8* )0xFFFFE49F)     
#define reg_MD0_1                       (*(u8* )0xFFFFE4B0)     
#define reg_MD0_2                       (*(u8* )0xFFFFE4B1)     
#define reg_MD0_3                       (*(u8* )0xFFFFE4B2)     
#define reg_MD0_4                       (*(u8* )0xFFFFE4B3)     
#define reg_MD0_5                       (*(u8* )0xFFFFE4B4)     
#define reg_MD0_6                       (*(u8* )0xFFFFE4B5)     
#define reg_MD0_7                       (*(u8* )0xFFFFE4B6)     
#define reg_MD0_8                       (*(u8* )0xFFFFE4B7)     
#define reg_MD1_1                       (*(u8* )0xFFFFE4B8)     
#define reg_MD1_2                       (*(u8* )0xFFFFE4B9)     
#define reg_MD1_3                       (*(u8* )0xFFFFE4BA)     
#define reg_MD1_4                       (*(u8* )0xFFFFE4BB)     
#define reg_MD1_5                       (*(u8* )0xFFFFE4BC)     
#define reg_MD1_6                       (*(u8* )0xFFFFE4BD)     
#define reg_MD1_7                       (*(u8* )0xFFFFE4BE)     
#define reg_MD1_8                       (*(u8* )0xFFFFE4BF)     
#define reg_MD2_1                       (*(u8* )0xFFFFE4C0)     
#define reg_MD2_2                       (*(u8* )0xFFFFE4C1)     
#define reg_MD2_3                       (*(u8* )0xFFFFE4C2)     
#define reg_MD2_4                       (*(u8* )0xFFFFE4C3)     
#define reg_MD2_5                       (*(u8* )0xFFFFE4C4)     
#define reg_MD2_6                       (*(u8* )0xFFFFE4C5)     
#define reg_MD2_7                       (*(u8* )0xFFFFE4C6)     
#define reg_MD2_8                       (*(u8* )0xFFFFE4C7)     
#define reg_MD3_1                       (*(u8* )0xFFFFE4C8)     
#define reg_MD3_2                       (*(u8* )0xFFFFE4C9)     
#define reg_MD3_3                       (*(u8* )0xFFFFE4CA)     
#define reg_MD3_4                       (*(u8* )0xFFFFE4CB)     
#define reg_MD3_5                       (*(u8* )0xFFFFE4CC)     
#define reg_MD3_6                       (*(u8* )0xFFFFE4CD)     
#define reg_MD3_7                       (*(u8* )0xFFFFE4CE)     
#define reg_MD3_8                       (*(u8* )0xFFFFE4CF)     
#define reg_MD4_1                       (*(u8* )0xFFFFE4D0)     
#define reg_MD4_2                       (*(u8* )0xFFFFE4D1)     
#define reg_MD4_3                       (*(u8* )0xFFFFE4D2)     
#define reg_MD4_4                       (*(u8* )0xFFFFE4D3)     
#define reg_MD4_5                       (*(u8* )0xFFFFE4D4)     
#define reg_MD4_6                       (*(u8* )0xFFFFE4D5)     
#define reg_MD4_7                       (*(u8* )0xFFFFE4D6)     
#define reg_MD4_8                       (*(u8* )0xFFFFE4D7)     
#define reg_MD5_1                       (*(u8* )0xFFFFE4D8)     
#define reg_MD5_2                       (*(u8* )0xFFFFE4D9)     
#define reg_MD5_3                       (*(u8* )0xFFFFE4DA)     
#define reg_MD5_4                       (*(u8* )0xFFFFE4DB)     
#define reg_MD5_5                       (*(u8* )0xFFFFE4DC)     
#define reg_MD5_6                       (*(u8* )0xFFFFE4DD)     
#define reg_MD5_7                       (*(u8* )0xFFFFE4DE)     
#define reg_MD5_8                       (*(u8* )0xFFFFE4DF)     
#define reg_MD6_1                       (*(u8* )0xFFFFE4E0)     
#define reg_MD6_2                       (*(u8* )0xFFFFE4E1)     
#define reg_MD6_3                       (*(u8* )0xFFFFE4E2)     
#define reg_MD6_4                       (*(u8* )0xFFFFE4E3)     
#define reg_MD6_5                       (*(u8* )0xFFFFE4E4)     
#define reg_MD6_6                       (*(u8* )0xFFFFE4E5)     
#define reg_MD6_7                       (*(u8* )0xFFFFE4E6)     
#define reg_MD6_8                       (*(u8* )0xFFFFE4E7)     
#define reg_MD7_1                       (*(u8* )0xFFFFE4E8)     
#define reg_MD7_2                       (*(u8* )0xFFFFE4E9)     
#define reg_MD7_3                       (*(u8* )0xFFFFE4EA)     
#define reg_MD7_4                       (*(u8* )0xFFFFE4EB)     
#define reg_MD7_5                       (*(u8* )0xFFFFE4EC)     
#define reg_MD7_6                       (*(u8* )0xFFFFE4ED)     
#define reg_MD7_7                       (*(u8* )0xFFFFE4EE)     
#define reg_MD7_8                       (*(u8* )0xFFFFE4EF)     
#define reg_MD8_1                       (*(u8* )0xFFFFE4F0)     
#define reg_MD8_2                       (*(u8* )0xFFFFE4F1)     
#define reg_MD8_3                       (*(u8* )0xFFFFE4F2)     
#define reg_MD8_4                       (*(u8* )0xFFFFE4F3)     
#define reg_MD8_5                       (*(u8* )0xFFFFE4F4)     
#define reg_MD8_6                       (*(u8* )0xFFFFE4F5)     
#define reg_MD8_7                       (*(u8* )0xFFFFE4F6)     
#define reg_MD8_8                       (*(u8* )0xFFFFE4F7)     
#define reg_MD9_1                       (*(u8* )0xFFFFE4F8)     
#define reg_MD9_2                       (*(u8* )0xFFFFE4F9)     
#define reg_MD9_3                       (*(u8* )0xFFFFE4FA)     
#define reg_MD9_4                       (*(u8* )0xFFFFE4FB)     
#define reg_MD9_5                       (*(u8* )0xFFFFE4FC)     
#define reg_MD9_6                       (*(u8* )0xFFFFE4FD)     
#define reg_MD9_7                       (*(u8* )0xFFFFE4FE)     
#define reg_MD9_8                       (*(u8* )0xFFFFE4FF)     
#define reg_MD10_1                      (*(u8* )0xFFFFE500)     
#define reg_MD10_2                      (*(u8* )0xFFFFE501)     
#define reg_MD10_3                      (*(u8* )0xFFFFE502)     
#define reg_MD10_4                      (*(u8* )0xFFFFE503)     
#define reg_MD10_5                      (*(u8* )0xFFFFE504)     
#define reg_MD10_6                      (*(u8* )0xFFFFE505)     
#define reg_MD10_7                      (*(u8* )0xFFFFE506)     
#define reg_MD10_8                      (*(u8* )0xFFFFE507)     
#define reg_MD11_1                      (*(u8* )0xFFFFE508)     
#define reg_MD11_2                      (*(u8* )0xFFFFE509)     
#define reg_MD11_3                      (*(u8* )0xFFFFE50A)     
#define reg_MD11_4                      (*(u8* )0xFFFFE50B)     
#define reg_MD11_5                      (*(u8* )0xFFFFE50C)     
#define reg_MD11_6                      (*(u8* )0xFFFFE50D)     
#define reg_MD11_7                      (*(u8* )0xFFFFE50E)     
#define reg_MD11_8                      (*(u8* )0xFFFFE50F)     
#define reg_MD12_1                      (*(u8* )0xFFFFE510)     
#define reg_MD12_2                      (*(u8* )0xFFFFE511)     
#define reg_MD12_3                      (*(u8* )0xFFFFE512)     
#define reg_MD12_4                      (*(u8* )0xFFFFE513)     
#define reg_MD12_5                      (*(u8* )0xFFFFE514)     
#define reg_MD12_6                      (*(u8* )0xFFFFE515)     
#define reg_MD12_7                      (*(u8* )0xFFFFE516)     
#define reg_MD12_8                      (*(u8* )0xFFFFE517)     
#define reg_MD13_1                      (*(u8* )0xFFFFE518)     
#define reg_MD13_2                      (*(u8* )0xFFFFE519)     
#define reg_MD13_3                      (*(u8* )0xFFFFE51A)     
#define reg_MD13_4                      (*(u8* )0xFFFFE51B)     
#define reg_MD13_5                      (*(u8* )0xFFFFE51C)     
#define reg_MD13_6                      (*(u8* )0xFFFFE51D)     
#define reg_MD13_7                      (*(u8* )0xFFFFE51E)     
#define reg_MD13_8                      (*(u8* )0xFFFFE51F)     
#define reg_MD14_1                      (*(u8* )0xFFFFE520)     
#define reg_MD14_2                      (*(u8* )0xFFFFE521)     
#define reg_MD14_3                      (*(u8* )0xFFFFE522)     
#define reg_MD14_4                      (*(u8* )0xFFFFE523)     
#define reg_MD14_5                      (*(u8* )0xFFFFE524)     
#define reg_MD14_6                      (*(u8* )0xFFFFE525)     
#define reg_MD14_7                      (*(u8* )0xFFFFE526)     
#define reg_MD14_8                      (*(u8* )0xFFFFE527)     
#define reg_MD15_1                      (*(u8* )0xFFFFE528)     
#define reg_MD15_2                      (*(u8* )0xFFFFE529)     
#define reg_MD15_3                      (*(u8* )0xFFFFE52A)     
#define reg_MD15_4                      (*(u8* )0xFFFFE52B)     
#define reg_MD15_5                      (*(u8* )0xFFFFE52C)     
#define reg_MD15_6                      (*(u8* )0xFFFFE52D)     
#define reg_MD15_7                      (*(u8* )0xFFFFE52E)     
#define reg_MD15_8                      (*(u8* )0xFFFFE52F)     

#define reg_FLMCR1                      (*(u8* )0xFFFFE800)                                                           
#define reg_FLMCR2                      (*(u8* )0xFFFFE801)                                                           
#define reg_EBR1                        (*(u8* )0xFFFFE802)     
#define reg_EBR2                        (*(u8* )0xFFFFE803)     

#define reg_UBARH                       (*(u16*)0xFFFFEC00)     
#define reg_UBARL                       (*(u16*)0xFFFFEC02)     
#define reg_UBAMRH                      (*(u16*)0xFFFFEC04)     
#define reg_UBAMRL                      (*(u16*)0xFFFFEC06)     
#define reg_UBBR                        (*(u16*)0xFFFFEC08)                                                           
#define reg_UBCR                        (*(u16*)0xFFFFEC0A)                                                           

#define reg_TCSR                        (*(u8* )0xFFFFEC10)                                                           
#define reg_TCNT                        (*(u8* )0xFFFFEC11)     
#define reg_RSTCSR_wr                   (*(u8* )0xFFFFEC12)                                                           
#define reg_RSTCSR_rd                   (*(u8* )0xFFFFEC13)                                                           
#define reg_SBYCR                       (*(u8* )0xFFFFEC14)                                                           

#define reg_BCR1                        (*(u16*)0xFFFFEC20)     
#define reg_BCR2                        (*(u16*)0xFFFFEC22)     
#define reg_WCR                         (*(u16*)0xFFFFEC24)     
#define reg_RAMER                       (*(u16*)0xFFFFEC26)                                                           
#define reg_DMAOR                       (*(u16*)0xFFFFECB0)                                                           

#define reg_SAR0                        (*(u32*)0xFFFFECC0)                                                           
#define reg_DAR0                        (*(u32*)0xFFFFECC4)                                                           
#define reg_DMATCR0                     (*(u32*)0xFFFFECC8)                                                           
#define reg_CHCR0                       (*(u32*)0xFFFFECCC)                                                           
#define reg_SAR1                        (*(u32*)0xFFFFECD0)                                                           
#define reg_DAR1                        (*(u32*)0xFFFFECD4)                                                           
#define reg_DMATCR1                     (*(u32*)0xFFFFECD8)                                                           
#define reg_CHCR1                       (*(u32*)0xFFFFECDC)                                                           
#define reg_SAR2                        (*(u32*)0xFFFFECE0)                                                           
#define reg_DAR2                        (*(u32*)0xFFFFECE4)                                                           
#define reg_DMATCR2                     (*(u32*)0xFFFFECE8)                                                           
#define reg_CHCR2                       (*(u32*)0xFFFFECEC)                                                           
#define reg_SAR3                        (*(u32*)0xFFFFECF0)                                                           
#define reg_DAR3                        (*(u32*)0xFFFFECF4)                                                           
#define reg_DMATCR3                     (*(u32*)0xFFFFECF8)                                                           
#define reg_CHCR3                       (*(u32*)0xFFFFECFC) 

#define reg_IPRA                        (*(u16*)0xFFFFED00)                                                           

#define reg_IPRC                        (*(u16*)0xFFFFED04)                                                           
#define reg_IPRD                        (*(u16*)0xFFFFED06)                                                           
#define reg_IPRE                        (*(u16*)0xFFFFED08)                                                           
#define reg_IPRF                        (*(u16*)0xFFFFED0A)                                                           
#define reg_IPRG                        (*(u16*)0xFFFFED0C)                                                           
#define reg_IPRH                        (*(u16*)0xFFFFED0E)                                                           
#define reg_IPRI                        (*(u16*)0xFFFFED10)                                                           
#define reg_IPRJ                        (*(u16*)0xFFFFED12)                                                           
#define reg_IPRK                        (*(u16*)0xFFFFED14)                                                           
#define reg_IPRL                        (*(u16*)0xFFFFED16)                                                           
#define reg_ICR                         (*(u16*)0xFFFFED18)                                                           
#define reg_ISR                         (*(u16*)0xFFFFED1A)                                                           


struct S_SCI
{
	byte SMR;
	byte BRR;
	byte SCR;
	byte TDR;
	byte SSR;
	byte RDR;
	byte SDCR;
};

#define reg_SCI0                        ((S_SCI*)0xFFFFF000)                                                            
#define reg_SCI1                        ((S_SCI*)0xFFFFF008)                                                            
#define reg_SCI2                        ((S_SCI*)0xFFFFF010)                                                            
#define reg_SCI3                        ((S_SCI*)0xFFFFF018)                                                            
#define reg_SCI4                        ((S_SCI*)0xFFFFF020)                                                            

#define reg_TSTR2                       (*(u8* )0xFFFFF400)                                                           
#define reg_TSTR1                       (*(u8* )0xFFFFF401)                                                           
#define reg_TSTR3                       (*(u8* )0xFFFFF402)                                                           

#define reg_PSCR1                       (*(u8* )0xFFFFF404)                                                           

#define reg_PSCR2                       (*(u8* )0xFFFFF406)                                                           

#define reg_PSCR3                       (*(u8* )0xFFFFF408)                                                           

#define reg_PSCR4                       (*(u8* )0xFFFFF40A)                                                           

#define reg_ICR0DH                      (*(u16*)0xFFFFF420)                                                           
#define reg_ICR0DL                      (*(u16*)0xFFFFF422)     
#define reg_ITVRR1                      (*(u16*)0xFFFFF424)                                                           
#define reg_ITVRR2A                     (*(u8* )0xFFFFF426)                                                           

#define reg_ITVRR2B                     (*(u8* )0xFFFFF428)                                                           

#define reg_TIOR0                       (*(u8* )0xFFFFF42A)                                                           

#define reg_TSR0                        (*(u16*)0xFFFFF42C)                                                           
#define reg_TIER0                       (*(u16*)0xFFFFF42E)                                                           
#define reg_TCNT0H                      (*(u16*)0xFFFFF430)     
#define reg_TCNT0L                      (*(u16*)0xFFFFF432)     

#define reg_ICR0A						(*(u32*)0xFFFFF434)                                                           
#define reg_ICR0AH                      (*(u16*)0xFFFFF434)                                                           
#define reg_ICR0AL                      (*(u16*)0xFFFFF436)     

#define reg_ICR0BH                      (*(u16*)0xFFFFF438)     
#define reg_ICR0BL                      (*(u16*)0xFFFFF43A)     
#define reg_ICR0CH                      (*(u16*)0xFFFFF43C)     
#define reg_ICR0CL                      (*(u16*)0xFFFFF43E)     
#define reg_TCNT1A                      (*(u16*)0xFFFFF440)     
#define reg_TCNT1B                      (*(u16*)0xFFFFF442)     
#define reg_GR1A                        (*(u16*)0xFFFFF444)     
#define reg_GR1B                        (*(u16*)0xFFFFF446)     
#define reg_GR1C                        (*(u16*)0xFFFFF448)     
#define reg_GR1D                        (*(u16*)0xFFFFF44A)     
#define reg_GR1E                        (*(u16*)0xFFFFF44C)     
#define reg_GR1F                        (*(u16*)0xFFFFF44E)     
#define reg_GR1G                        (*(u16*)0xFFFFF450)     
#define reg_GR1H                        (*(u16*)0xFFFFF452)     
#define reg_OCR1                        (*(u16*)0xFFFFF454)     
#define reg_OSBR1                       (*(u16*)0xFFFFF456)     
#define reg_TIOR1B                      (*(u8* )0xFFFFF458)                                                           
#define reg_TIOR1A                      (*(u8* )0xFFFFF459)                                                           
#define reg_TIOR1D                      (*(u8* )0xFFFFF45A)                                                           
#define reg_TIOR1C                      (*(u8* )0xFFFFF45B)                                                           
#define reg_TCR1B                       (*(u8* )0xFFFFF45C)                                                           
#define reg_TCR1A                       (*(u8* )0xFFFFF45D)                                                           
#define reg_TSR1A                       (*(u8* )0xFFFFF45E)                                                           
#define reg_IMF1H                       (*(u8* )0xFFFFF45F)     
#define reg_TSR1B                       (*(u16*)0xFFFFF460)     
#define reg_TIER1A                      (*(u16*)0xFFFFF462)                                                           
#define reg_TIER1B                      (*(u16*)0xFFFFF464)                                                           
#define reg_TRGMDR                      (*(u8* )0xFFFFF466)     
#define reg_TSR3                        (*(u16*)0xFFFFF480)                                                           
#define reg_TIER3                       (*(u16*)0xFFFFF482)                                                           
#define reg_TMDR                        (*(u8* )0xFFFFF484)                                                           
#define reg_TCNT3                       (*(u16*)0xFFFFF4A0)     
#define reg_GR3A                        (*(u16*)0xFFFFF4A2)     
#define reg_GR3B                        (*(u16*)0xFFFFF4A4)     
#define reg_GR3C                        (*(u16*)0xFFFFF4A6)     
#define reg_GR3D                        (*(u16*)0xFFFFF4A8)                                                           
#define reg_TIOR3B                      (*(u8* )0xFFFFF4AA)                                                           
#define reg_TIOR3A                      (*(u8* )0xFFFFF4AB)                                                           
#define reg_TCR3                        (*(u8* )0xFFFFF4AC)                                                           
#define reg_TCNT4                       (*(u16*)0xFFFFF4C0)     
#define reg_GR4A                        (*(u16*)0xFFFFF4C2)     
#define reg_GR4B                        (*(u16*)0xFFFFF4C4)     
#define reg_GR4C                        (*(u16*)0xFFFFF4C6)     
#define reg_GR4D                        (*(u16*)0xFFFFF4C8)     
#define reg_TIOR4B                      (*(u8* )0xFFFFF4CA)                                                           
#define reg_TIOR4A                      (*(u8* )0xFFFFF4CB)                                                           
#define reg_TCR4                        (*(u8* )0xFFFFF4CC)                                                           
#define reg_TCNT5                       (*(u16*)0xFFFFF4E0)                                                           
#define reg_GR5A                        (*(u16*)0xFFFFF4E2)                                                           
#define reg_GR5B                        (*(u16*)0xFFFFF4E4)     
#define reg_GR5C                        (*(u16*)0xFFFFF4E6)     
#define reg_GR5D                        (*(u16*)0xFFFFF4E8)     
#define reg_TIOR5B                      (*(u8* )0xFFFFF4EA)                                                           
#define reg_TIOR5A                      (*(u8* )0xFFFFF4EB)                                                           
#define reg_TCR5                        (*(u8* )0xFFFFF4EC)                                                           
#define reg_TCNT6A                      (*(u16*)0xFFFFF500)                                                           
#define reg_TCNT6B                      (*(u16*)0xFFFFF502)                                                           
#define reg_TCNT6C                      (*(u16*)0xFFFFF504)                                                           
#define reg_TCNT6D                      (*(u16*)0xFFFFF506)                                                           
#define reg_CYLR6A                      (*(u16*)0xFFFFF508)                                                           
#define reg_CYLR6B                      (*(u16*)0xFFFFF50A)                                                           
#define reg_CYLR6C                      (*(u16*)0xFFFFF50C)                                                           
#define reg_CYLR6D                      (*(u16*)0xFFFFF50E)                                                           
#define reg_BFR6A                       (*(u16*)0xFFFFF510)                                                           
#define reg_BFR6B                       (*(u16*)0xFFFFF512)                                                           
#define reg_BFR6C                       (*(u16*)0xFFFFF514)                                                           
#define reg_BFR6D                       (*(u16*)0xFFFFF516)                                                           
#define reg_DTR6A                       (*(u16*)0xFFFFF518)                                                           
#define reg_DTR6B                       (*(u16*)0xFFFFF51A)                                                           
#define reg_DTR6C                       (*(u16*)0xFFFFF51C)                                                           
#define reg_DTR6D                       (*(u16*)0xFFFFF51E)                                                           
#define reg_TCR6B                       (*(u8* )0xFFFFF520)                                                           
#define reg_TCR6A                       (*(u8* )0xFFFFF521)                                                           
#define reg_TSR6                        (*(u16*)0xFFFFF522)     
#define reg_TIER6                       (*(u16*)0xFFFFF524)                                                           
#define reg_PMDR                        (*(u8* )0xFFFFF526)                                                           
#define reg_TCNT7A                      (*(u16*)0xFFFFF580)                                                           
#define reg_TCNT7B                      (*(u16*)0xFFFFF582)                                                           
#define reg_TCNT7C                      (*(u16*)0xFFFFF584)                                                           
#define reg_TCNT7D                      (*(u16*)0xFFFFF586)                                                           
#define reg_CYLR7A                      (*(u16*)0xFFFFF588)                                                           
#define reg_CYLR7B                      (*(u16*)0xFFFFF58A)     
#define reg_CYLR7C                      (*(u16*)0xFFFFF58C)     
#define reg_CYLR7D                      (*(u16*)0xFFFFF58E)     
#define reg_BFR7A                       (*(u16*)0xFFFFF590)                                                           
#define reg_BFR7B                       (*(u16*)0xFFFFF592)                                                           
#define reg_BFR7C                       (*(u16*)0xFFFFF594)                                                           
#define reg_BFR7D                       (*(u16*)0xFFFFF596)                                                           
#define reg_DTR7A                       (*(u16*)0xFFFFF598)                                                           
#define reg_DTR7B                       (*(u16*)0xFFFFF59A)                                                           
#define reg_DTR7C                       (*(u16*)0xFFFFF59C)                                                           
#define reg_DTR7D                       (*(u16*)0xFFFFF59E)                                                           
#define reg_TCR7B                       (*(u8* )0xFFFFF5A0)                                                           
#define reg_TCR7A                       (*(u8* )0xFFFFF5A1)                                                           
#define reg_TSR7                        (*(u16*)0xFFFFF5A2)     
#define reg_TIER7                       (*(u16*)0xFFFFF5A4)                                                           
#define reg_TCNT11                      (*(u16*)0xFFFFF5C0)     
#define reg_GR11A                       (*(u16*)0xFFFFF5C2)     
#define reg_GR11B                       (*(u16*)0xFFFFF5C4)     
#define reg_TIOR11                      (*(u8* )0xFFFFF5C6)                                                           
#define reg_TCR11                       (*(u8* )0xFFFFF5C8)                                                           
#define reg_TSR11                       (*(u16*)0xFFFFF5CA)                                                           
#define reg_TIER11                      (*(u16*)0xFFFFF5CC)                                                           
#define reg_TCNT2A                      (*(u16*)0xFFFFF600)                                                           
#define reg_TCNT2B                      (*(u16*)0xFFFFF602)                                                           
#define reg_GR2A                        (*(u16*)0xFFFFF604)                                                           
#define reg_GR2B                        (*(u16*)0xFFFFF606)     
#define reg_GR2C                        (*(u16*)0xFFFFF608)                                                           
#define reg_GR2D                        (*(u16*)0xFFFFF60A)                                                           
#define reg_GR2E                        (*(u16*)0xFFFFF60C)                                                           
#define reg_GR2F                        (*(u16*)0xFFFFF60E)                                                           
#define reg_GR2G                        (*(u16*)0xFFFFF610)                                                           
#define reg_GR2H                        (*(u16*)0xFFFFF612)                                                           
#define reg_OCR2A                       (*(u16*)0xFFFFF614)     
#define reg_OCR2B                       (*(u16*)0xFFFFF616)     
#define reg_OCR2C                       (*(u16*)0xFFFFF618)     
#define reg_OCR2D                       (*(u16*)0xFFFFF61A)     
#define reg_OCR2E                       (*(u16*)0xFFFFF61C)     
#define reg_OCR2F                       (*(u16*)0xFFFFF61E)     
#define reg_OCR2G                       (*(u16*)0xFFFFF620)                                                           
#define reg_OCR2H                       (*(u16*)0xFFFFF622)                                                           
#define reg_OSBR2                       (*(u16*)0xFFFFF624)                                                           
#define reg_TIOR2B                      (*(u8* )0xFFFFF626)                                                           
#define reg_TIOR2A                      (*(u8* )0xFFFFF627)                                                           
#define reg_TIOR2D                      (*(u8* )0xFFFFF628)                                                           
#define reg_TIOR2C                      (*(u8* )0xFFFFF629)                                                           
#define reg_TCR2B                       (*(u8* )0xFFFFF62A)                                                           
#define reg_TCR2A                       (*(u8* )0xFFFFF62B)                                                           
#define reg_TSR2A                       (*(u16*)0xFFFFF62C)                                                           
#define reg_TSR2B                       (*(u16*)0xFFFFF62E)                                                           
#define reg_TIER2A                      (*(u16*)0xFFFFF630)                                                           
#define reg_TIER2B                      (*(u16*)0xFFFFF632)                                                           
#define reg_DCNT8A                      (*(u16*)0xFFFFF640)                                                           
#define reg_DNCT8B                      (*(u16*)0xFFFFF642)                                                           
#define reg_DNCT8C                      (*(u16*)0xFFFFF644)                                                           
#define reg_DCNT8D                      (*(u16*)0xFFFFF646)                                                           
#define reg_DCNT8E                      (*(u16*)0xFFFFF648)                                                           
#define reg_DCNT8F                      (*(u16*)0xFFFFF64A)                                                           
#define reg_DCNT8G                      (*(u16*)0xFFFFF64C)                                                           
#define reg_DCNT8H                      (*(u16*)0xFFFFF64E)                                                           
#define reg_DCNT8I                      (*(u16*)0xFFFFF650)                                                           
#define reg_DCNT8J                      (*(u16*)0xFFFFF652)                                                           
#define reg_DCNT8K                      (*(u16*)0xFFFFF654)                                                           
#define reg_DCNT8L                      (*(u16*)0xFFFFF656)                                                           
#define reg_DCNT8M                      (*(u16*)0xFFFFF658)                                                           
#define reg_DCNT8N                      (*(u16*)0xFFFFF65A)                                                           
#define reg_DCNT8O                      (*(u16*)0xFFFFF65C)                                                           
#define reg_DCNT8P                      (*(u16*)0xFFFFF65E)                                                           
#define reg_RLDR8                       (*(u16*)0xFFFFF660)     
#define reg_TCNR                        (*(u16*)0xFFFFF662)                                                           
#define reg_OTR                         (*(u16*)0xFFFFF664)                                                           
#define reg_DSTR                        (*(u16*)0xFFFFF666)                                                           
#define reg_TCR8                        (*(u8* )0xFFFFF668)                                                           
#define reg_TSR8                        (*(u16*)0xFFFFF66A)                                                           
#define reg_TIER8                       (*(u16*)0xFFFFF66C)                                                           
#define reg_RLDENR                      (*(u8* )0xFFFFF66E)                                                           
#define reg_ECNT9A                      (*(u8* )0xFFFFF680)                                                           
#define reg_ECNT9B                      (*(u8* )0xFFFFF682)     
#define reg_ECNT9C                      (*(u8* )0xFFFFF684)     
#define reg_ECNT9D                      (*(u8* )0xFFFFF686)                                                           
#define reg_ECNT9E                      (*(u8* )0xFFFFF688)                                                           
#define reg_ECNT9F                      (*(u8* )0xFFFFF68A)                                                           
#define reg_GR9A                        (*(u8* )0xFFFFF68C)                                                           
#define reg_GR9B                        (*(u8* )0xFFFFF68E)     
#define reg_GR9C                        (*(u8* )0xFFFFF690)     
#define reg_GR9D                        (*(u8* )0xFFFFF692)                                                           
#define reg_GR9E                        (*(u8* )0xFFFFF694)                                                           
#define reg_GR9F                        (*(u8* )0xFFFFF696)                                                           
#define reg_TCR9A                       (*(u8* )0xFFFFF698)                                                           
#define reg_TCR9B                       (*(u8* )0xFFFFF69A)                                                           
#define reg_TCR9C                       (*(u8* )0xFFFFF69C)                                                           
#define reg_TSR9                        (*(u16*)0xFFFFF69E)                                                           
#define reg_TIER9                       (*(u16*)0xFFFFF6A0)                                                           
#define reg_TCNT10AH                    (*(u16*)0xFFFFF6C0)     
#define reg_TCNT10AL                    (*(u16*)0xFFFFF6C2)     
#define reg_TCNT10B                     (*(u8* )0xFFFFF6C4)     
#define reg_TCNT10C                     (*(u16*)0xFFFFF6C6)     
#define reg_TCNT10D                     (*(u8* )0xFFFFF6C8)     
#define reg_TCNT10E                     (*(u16*)0xFFFFF6CA)     
#define reg_TCNT10F                     (*(u16*)0xFFFFF6CC)     
#define reg_TCNT10G                     (*(u16*)0xFFFFF6CE)     
#define reg_ICR10AH                     (*(u16*)0xFFFFF6D0)     
#define reg_ICR10AL                     (*(u16*)0xFFFFF6D2)     
#define reg_OCR10AH                     (*(u16*)0xFFFFF6D4)     
#define reg_OCR10AL                     (*(u16*)0xFFFFF6D6)     
#define reg_OCR10B                      (*(u8* )0xFFFFF6D8)     
#define reg_RLD10C                      (*(u16*)0xFFFFF6DA)     
#define reg_GR10G                       (*(u16*)0xFFFFF6DC)     
#define reg_TCNT10H                     (*(u8* )0xFFFFF6DE)     
#define reg_NCR10                       (*(u8* )0xFFFFF6E0)     
#define reg_TIOR10                      (*(u8* )0xFFFFF6E2)                                                           
#define reg_TCR10                       (*(u8* )0xFFFFF6E4)                                                           
#define reg_TCCLR10                     (*(u16*)0xFFFFF6E6)     
#define reg_TSR10                       (*(u16*)0xFFFFF6E8)     
#define reg_TIER10                      (*(u16*)0xFFFFF6EA)                                                           
#define reg_POPCR                       (*(u16*)0xFFFFF700)                                                           
#define reg_SYSCR                       (*(u8* )0xFFFFF708)                                                           
#define reg_MSTCR_wr                    (*(u8* )0xFFFFF70A)                                                           
#define reg_MSTCR_rd                    (*(u8* )0xFFFFF70B)     
#define reg_CMSTR                       (*(u16*)0xFFFFF710)                                                           
#define reg_CMCSR0                      (*(u16*)0xFFFFF712)                                                           
#define reg_CMCNT0                      (*(u16*)0xFFFFF714)     
#define reg_CMCOR0                      (*(u16*)0xFFFFF716)                                                           
#define reg_CMCSR1                      (*(u16*)0xFFFFF718)                                                           
#define reg_CMCNT1                      (*(u16*)0xFFFFF71A)     
#define reg_CMCOR1                      (*(u16*)0xFFFFF71C)     
#define reg_PAIOR                       (*(u16*)0xFFFFF720)                                                           
#define reg_PACRH                       (*(u16*)0xFFFFF722)                                                           
#define reg_PACRL                       (*(u16*)0xFFFFF724)                                                           
#define reg_PADRH                       (*(u8* )0xFFFFF726)                                                           
#define reg_PADRL                       (*(u8* )0xFFFFF727)                                                           
#define reg_PHIOR                       (*(u16*)0xFFFFF728)                                                           
#define reg_PHCR                        (*(u16*)0xFFFFF72A)                                                           
#define reg_PHDRH                       (*(u8* )0xFFFFF72C)                                                           
#define reg_PHDRL                       (*(u8* )0xFFFFF72D)                                                           
#define reg_ADTRGR1                     (*(u8* )0xFFFFF72E)     
#define reg_PBIOR                       (*(u16*)0xFFFFF730)                                                           
#define reg_PBCRH                       (*(u16*)0xFFFFF732)                                                           
#define reg_PBCRL                       (*(u16*)0xFFFFF734)                                                           
#define reg_PBIR                        (*(u16*)0xFFFFF736)                                                           
#define reg_PBDRH                       (*(u8* )0xFFFFF738)                                                           
#define reg_PBDRL                       (*(u8* )0xFFFFF739)                                                           
#define reg_PCIOR                       (*(u16*)0xFFFFF73A)     
#define reg_PCCR                        (*(u16*)0xFFFFF73C)                                                           
#define reg_PCDR                        (*(u16*)0xFFFFF73E)     
#define reg_PDIOR                       (*(u16*)0xFFFFF740)                                                           
#define reg_PDCRH                       (*(u16*)0xFFFFF742)                                                           
#define reg_PDCRL                       (*(u16*)0xFFFFF744)                                                           
#define reg_PDDRH                       (*(u8* )0xFFFFF746)     
#define reg_PDDRL                       (*(u8* )0xFFFFF747)     
#define reg_PFIOR                       (*(u16*)0xFFFFF748)                                                           
#define reg_PFCRH                       (*(u16*)0xFFFFF74A)                                                           
#define reg_PFCRL                       (*(u16*)0xFFFFF74C)                                                           
#define reg_PFDRH                       (*(u8* )0xFFFFF74E)                                                           
#define reg_PFDRL                       (*(u8* )0xFFFFF74F)                                                           
#define reg_PEIOR                       (*(u16*)0xFFFFF750)                                                           
#define reg_PECR                        (*(u16*)0xFFFFF752)                                                           
#define reg_PEDRH                       (*(u8* )0xFFFFF754)                                                           
#define reg_PEDRL                       (*(u8* )0xFFFFF755)                                                           
#define reg_PLDRH                       (*(u8* )0xFFFFF75E)                                                           
#define reg_PLDRL                       (*(u8* )0xFFFFF75F)                                                           
#define reg_PGIOR                       (*(u16*)0xFFFFF760)                                                           
#define reg_PGCR                        (*(u16*)0xFFFFF762)                                                           
#define reg_PGDRH                       (*(u8* )0xFFFFF764)                                                           
#define reg_PGDRL                       (*(u8* )0xFFFFF765)                                                           
#define reg_PJIOR                       (*(u16*)0xFFFFF766)     
#define reg_PJCRH                       (*(u16*)0xFFFFF768)                                                           
#define reg_PJCRL                       (*(u16*)0xFFFFF76A)                                                           
#define reg_PJDRH                       (*(u8* )0xFFFFF76C)                                                           
#define reg_PJDRL                       (*(u8* )0xFFFFF76D)                                                           
#define reg_ADTRGR0                     (*(u8* )0xFFFFF76E)     
#define reg_PKIOR                       (*(u16*)0xFFFFF770)                                                           
#define reg_PKCRH                       (*(u16*)0xFFFFF772)                                                           
#define reg_PKCRL                       (*(u16*)0xFFFFF774)                                                           
#define reg_PKIR                        (*(u16*)0xFFFFF776)                                                           
#define reg_PKDRH                       (*(u8* )0xFFFFF778)                                                           
#define reg_PKDRL                       (*(u8* )0xFFFFF779)                                                           
#define reg_to                          (*(u8* )0xFFFFF77A)     
#define reg_ADDR0H                      (*(u8* )0xFFFFF800)                                                           
#define reg_ADDR0L                      (*(u8* )0xFFFFF801)     
#define reg_ADDR1H                      (*(u8* )0xFFFFF802)     
#define reg_ADDR1L                      (*(u8* )0xFFFFF803)     
#define reg_ADDR2H                      (*(u8* )0xFFFFF804)     
#define reg_ADDR2L                      (*(u8* )0xFFFFF805)     
#define reg_ADDR3H                      (*(u8* )0xFFFFF806)     
#define reg_ADDR3L                      (*(u8* )0xFFFFF807)     
#define reg_ADDR4H                      (*(u8* )0xFFFFF808)     
#define reg_ADDR4L                      (*(u8* )0xFFFFF809)     
#define reg_ADDR5H                      (*(u8* )0xFFFFF80A)     
#define reg_ADDR5L                      (*(u8* )0xFFFFF80B)     
#define reg_ADDR6H                      (*(u8* )0xFFFFF80C)     
#define reg_ADDR6L                      (*(u8* )0xFFFFF80D)     
#define reg_ADDR7H                      (*(u8* )0xFFFFF80E)     
#define reg_ADDR7L                      (*(u8* )0xFFFFF80F)                                                           
#define reg_ADDR8H                      (*(u8* )0xFFFFF810)     
#define reg_ADDR8L                      (*(u8* )0xFFFFF811)     
#define reg_ADDR9H                      (*(u8* )0xFFFFF812)     
#define reg_ADDR9L                      (*(u8* )0xFFFFF813)     
#define reg_ADDR10H                     (*(u8* )0xFFFFF814)     
#define reg_ADDR10L                     (*(u8* )0xFFFFF815)     
#define reg_ADDR11H                     (*(u8* )0xFFFFF816)     
#define reg_ADDR11L                     (*(u8* )0xFFFFF817)     
#define reg_ADCSR0                      (*(u8* )0xFFFFF818)                                                           
#define reg_ADCR0                       (*(u8* )0xFFFFF819)                                                           
#define reg_ADDR12H                     (*(u8* )0xFFFFF820)     
#define reg_ADDR12L                     (*(u8* )0xFFFFF821)     
#define reg_ADDR13H                     (*(u8* )0xFFFFF822)     
#define reg_ADDR13L                     (*(u8* )0xFFFFF823)     
#define reg_ADDR14H                     (*(u8* )0xFFFFF824)     
#define reg_ADDR14L                     (*(u8* )0xFFFFF825)     
#define reg_ADDR15H                     (*(u8* )0xFFFFF826)     
#define reg_ADDR15L                     (*(u8* )0xFFFFF827)     

#endif // HWREG_H__24_06_2017__23_34

